version: 2
jobs:
  build:
    working_directory: ~/Clever/clever-php
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - setup_remote_docker
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run: curl -sS https://getcomposer.org/installer | php
    - run: php composer.phar install --prefer-dist --no-interaction --no-progress
    - run: ./vendor/bin/phpunit
    - run:
        command: |-
          cd /tmp/ && wget https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
          sudo apt-get update
          sudo apt-get install python-dev
          sudo pip install --upgrade awscli && aws --version
          pip install --upgrade --user awscli
        name: Install awscli for ECR publish
