# Clear out the old files
rm -rf docs/
rm -rf test/
rm -rf lib/

# Copy autogenerated files into root directory and rename
cp -R SwaggerClient-php/. . || true
rm -rf SwaggerClient-php || true

# Rename references of swagger client to Clever
git grep -l 'Swagger\\Client' -- './*' ':(exclude)override/override.sh' | xargs sed -i "" 's/Swagger\\Client/Clever/g'
git grep -l 'Swagger\\\\Client' -- './*' ':(exclude)override/override.sh' | xargs sed -i "" 's/Swagger\\\\Client/Clever/g'

# Copy override files for events
cp override/ObjectSerializer.php lib/

# Update the README
mv README.md docs/README.md
sed -i "" 's/## Documentation for API Endpoints/<EOD>\'$'\n## Documentation for API Endpoints/g' docs/README.md
sed -i "" '/# SwaggerClient-php/,/<EOD>/d' docs/README.md
sed -i "" '/## Author/d' docs/README.md
sed -i "" 's/docs\///g' docs/README.md
git grep -l '../README.md' -- './docs/*' | xargs sed -i "" 's/..\/README.md/README.md/g'
# These links never actually worked!
git grep -l 'README.md' -- './docs/Model/*' | xargs sed -i "" 's/README.md/..\/README.md/g'
cp override/README.md README.md
cp override/EventsApiClassTest.php test/Api/EventsApiClassTest.php
