<?php
/**
 * DistrictTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clever
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Clever;

/**
 * DistrictTest Class Doc Comment
 *
 * @category    Class */
// * @description District
/**
 * @package     Clever
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DistrictTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "District"
     */
    public function testDistrict()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_sync"
     */
    public function testPropertyLastSync()
    {
    }

    /**
     * Test attribute "launch_date"
     */
    public function testPropertyLaunchDate()
    {
    }

    /**
     * Test attribute "mdr_number"
     */
    public function testPropertyMdrNumber()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "nces_id"
     */
    public function testPropertyNcesId()
    {
    }

    /**
     * Test attribute "pause_end"
     */
    public function testPropertyPauseEnd()
    {
    }

    /**
     * Test attribute "pause_start"
     */
    public function testPropertyPauseStart()
    {
    }

    /**
     * Test attribute "sis_type"
     */
    public function testPropertySisType()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }
}
