<?php
/**
 * NameTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clever
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Clever;

/**
 * NameTest Class Doc Comment
 *
 * @category    Class */
// * @description Name
/**
 * @package     Clever
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NameTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Name"
     */
    public function testName()
    {
    }

    /**
     * Test attribute "first"
     */
    public function testPropertyFirst()
    {
    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {
    }

    /**
     * Test attribute "middle"
     */
    public function testPropertyMiddle()
    {
    }
}
