<?php
/**
 * SectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clever
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Clever;

/**
 * SectionTest Class Doc Comment
 *
 * @category    Class */
// * @description Section
/**
 * @package     Clever
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Section"
     */
    public function testSection()
    {
    }

    /**
     * Test attribute "course"
     */
    public function testPropertyCourse()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "district"
     */
    public function testPropertyDistrict()
    {
    }

    /**
     * Test attribute "grade"
     */
    public function testPropertyGrade()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "period"
     */
    public function testPropertyPeriod()
    {
    }

    /**
     * Test attribute "school"
     */
    public function testPropertySchool()
    {
    }

    /**
     * Test attribute "section_number"
     */
    public function testPropertySectionNumber()
    {
    }

    /**
     * Test attribute "sis_id"
     */
    public function testPropertySisId()
    {
    }

    /**
     * Test attribute "students"
     */
    public function testPropertyStudents()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "teacher"
     */
    public function testPropertyTeacher()
    {
    }

    /**
     * Test attribute "teachers"
     */
    public function testPropertyTeachers()
    {
    }

    /**
     * Test attribute "term_id"
     */
    public function testPropertyTermId()
    {
    }
}
