<?php
/**
 * StudentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clever
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Clever;

/**
 * StudentTest Class Doc Comment
 *
 * @category    Class */
// * @description Student
/**
 * @package     Clever
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StudentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Student"
     */
    public function testStudent()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "credentials"
     */
    public function testPropertyCredentials()
    {
    }

    /**
     * Test attribute "district"
     */
    public function testPropertyDistrict()
    {
    }

    /**
     * Test attribute "dob"
     */
    public function testPropertyDob()
    {
    }

    /**
     * Test attribute "ell_status"
     */
    public function testPropertyEllStatus()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "grade"
     */
    public function testPropertyGrade()
    {
    }

    /**
     * Test attribute "graduation_year"
     */
    public function testPropertyGraduationYear()
    {
    }

    /**
     * Test attribute "hispanic_ethnicity"
     */
    public function testPropertyHispanicEthnicity()
    {
    }

    /**
     * Test attribute "home_language"
     */
    public function testPropertyHomeLanguage()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "iep_status"
     */
    public function testPropertyIepStatus()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "race"
     */
    public function testPropertyRace()
    {
    }

    /**
     * Test attribute "school"
     */
    public function testPropertySchool()
    {
    }

    /**
     * Test attribute "schools"
     */
    public function testPropertySchools()
    {
    }

    /**
     * Test attribute "sis_id"
     */
    public function testPropertySisId()
    {
    }

    /**
     * Test attribute "state_id"
     */
    public function testPropertyStateId()
    {
    }

    /**
     * Test attribute "student_number"
     */
    public function testPropertyStudentNumber()
    {
    }

    /**
     * Test attribute "unweighted_gpa"
     */
    public function testPropertyUnweightedGpa()
    {
    }

    /**
     * Test attribute "weighted_gpa"
     */
    public function testPropertyWeightedGpa()
    {
    }
}
