<?php
/**
 * DataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Clever
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Clever;

use \Clever\Configuration;
use \Clever\ApiException;
use \Clever\ObjectSerializer;

/**
 * DataApiTest Class Doc Comment
 *
 * @category Class
 * @package  Clever
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getContact
     *
     * .
     *
     */
    public function testGetContact()
    {
    }

    /**
     * Test case for getContacts
     *
     * .
     *
     */
    public function testGetContacts()
    {
    }

    /**
     * Test case for getContactsForStudent
     *
     * .
     *
     */
    public function testGetContactsForStudent()
    {
    }

    /**
     * Test case for getCourse
     *
     * .
     *
     */
    public function testGetCourse()
    {
    }

    /**
     * Test case for getCourseForSection
     *
     * .
     *
     */
    public function testGetCourseForSection()
    {
    }

    /**
     * Test case for getCourses
     *
     * .
     *
     */
    public function testGetCourses()
    {
    }

    /**
     * Test case for getDistrict
     *
     * .
     *
     */
    public function testGetDistrict()
    {
    }

    /**
     * Test case for getDistrictAdmin
     *
     * .
     *
     */
    public function testGetDistrictAdmin()
    {
    }

    /**
     * Test case for getDistrictAdmins
     *
     * .
     *
     */
    public function testGetDistrictAdmins()
    {
    }

    /**
     * Test case for getDistrictForContact
     *
     * .
     *
     */
    public function testGetDistrictForContact()
    {
    }

    /**
     * Test case for getDistrictForCourse
     *
     * .
     *
     */
    public function testGetDistrictForCourse()
    {
    }

    /**
     * Test case for getDistrictForDistrictAdmin
     *
     * .
     *
     */
    public function testGetDistrictForDistrictAdmin()
    {
    }

    /**
     * Test case for getDistrictForSchool
     *
     * .
     *
     */
    public function testGetDistrictForSchool()
    {
    }

    /**
     * Test case for getDistrictForSchoolAdmin
     *
     * .
     *
     */
    public function testGetDistrictForSchoolAdmin()
    {
    }

    /**
     * Test case for getDistrictForSection
     *
     * .
     *
     */
    public function testGetDistrictForSection()
    {
    }

    /**
     * Test case for getDistrictForStudent
     *
     * .
     *
     */
    public function testGetDistrictForStudent()
    {
    }

    /**
     * Test case for getDistrictForTeacher
     *
     * .
     *
     */
    public function testGetDistrictForTeacher()
    {
    }

    /**
     * Test case for getDistrictForTerm
     *
     * .
     *
     */
    public function testGetDistrictForTerm()
    {
    }

    /**
     * Test case for getDistricts
     *
     * .
     *
     */
    public function testGetDistricts()
    {
    }

    /**
     * Test case for getSchool
     *
     * .
     *
     */
    public function testGetSchool()
    {
    }

    /**
     * Test case for getSchoolAdmin
     *
     * .
     *
     */
    public function testGetSchoolAdmin()
    {
    }

    /**
     * Test case for getSchoolAdmins
     *
     * .
     *
     */
    public function testGetSchoolAdmins()
    {
    }

    /**
     * Test case for getSchoolForSection
     *
     * .
     *
     */
    public function testGetSchoolForSection()
    {
    }

    /**
     * Test case for getSchoolForStudent
     *
     * .
     *
     */
    public function testGetSchoolForStudent()
    {
    }

    /**
     * Test case for getSchoolForTeacher
     *
     * .
     *
     */
    public function testGetSchoolForTeacher()
    {
    }

    /**
     * Test case for getSchools
     *
     * .
     *
     */
    public function testGetSchools()
    {
    }

    /**
     * Test case for getSchoolsForSchoolAdmin
     *
     * .
     *
     */
    public function testGetSchoolsForSchoolAdmin()
    {
    }

    /**
     * Test case for getSchoolsForStudent
     *
     * .
     *
     */
    public function testGetSchoolsForStudent()
    {
    }

    /**
     * Test case for getSchoolsForTeacher
     *
     * .
     *
     */
    public function testGetSchoolsForTeacher()
    {
    }

    /**
     * Test case for getSection
     *
     * .
     *
     */
    public function testGetSection()
    {
    }

    /**
     * Test case for getSections
     *
     * .
     *
     */
    public function testGetSections()
    {
    }

    /**
     * Test case for getSectionsForCourse
     *
     * .
     *
     */
    public function testGetSectionsForCourse()
    {
    }

    /**
     * Test case for getSectionsForSchool
     *
     * .
     *
     */
    public function testGetSectionsForSchool()
    {
    }

    /**
     * Test case for getSectionsForStudent
     *
     * .
     *
     */
    public function testGetSectionsForStudent()
    {
    }

    /**
     * Test case for getSectionsForTeacher
     *
     * .
     *
     */
    public function testGetSectionsForTeacher()
    {
    }

    /**
     * Test case for getSectionsForTerm
     *
     * .
     *
     */
    public function testGetSectionsForTerm()
    {
    }

    /**
     * Test case for getStudent
     *
     * .
     *
     */
    public function testGetStudent()
    {
    }

    /**
     * Test case for getStudents
     *
     * .
     *
     */
    public function testGetStudents()
    {
    }

    /**
     * Test case for getStudentsForContact
     *
     * .
     *
     */
    public function testGetStudentsForContact()
    {
    }

    /**
     * Test case for getStudentsForSchool
     *
     * .
     *
     */
    public function testGetStudentsForSchool()
    {
    }

    /**
     * Test case for getStudentsForSection
     *
     * .
     *
     */
    public function testGetStudentsForSection()
    {
    }

    /**
     * Test case for getStudentsForTeacher
     *
     * .
     *
     */
    public function testGetStudentsForTeacher()
    {
    }

    /**
     * Test case for getTeacher
     *
     * .
     *
     */
    public function testGetTeacher()
    {
    }

    /**
     * Test case for getTeacherForSection
     *
     * .
     *
     */
    public function testGetTeacherForSection()
    {
    }

    /**
     * Test case for getTeachers
     *
     * .
     *
     */
    public function testGetTeachers()
    {
    }

    /**
     * Test case for getTeachersForSchool
     *
     * .
     *
     */
    public function testGetTeachersForSchool()
    {
    }

    /**
     * Test case for getTeachersForSection
     *
     * .
     *
     */
    public function testGetTeachersForSection()
    {
    }

    /**
     * Test case for getTeachersForStudent
     *
     * .
     *
     */
    public function testGetTeachersForStudent()
    {
    }

    /**
     * Test case for getTerm
     *
     * .
     *
     */
    public function testGetTerm()
    {
    }

    /**
     * Test case for getTermForSection
     *
     * .
     *
     */
    public function testGetTermForSection()
    {
    }

    /**
     * Test case for getTerms
     *
     * .
     *
     */
    public function testGetTerms()
    {
    }
}
